apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: we
  janus-idp.io/tekton: we
  backstage.io/kubernetes-id: we
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: we
resources:
- deployment.yaml
- route.yaml
- service.yaml
